// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.flamecast.dev' | (string & {});
};

export type AgentsList = {
    agents: Array<AgentMeta>;
};

export type AgentMeta = {
    id: Uuid;
    name: string;
    slug: Slug;
    /**
     * Workspace this agent belongs to. NULL only on legacy agents created before the workspace primitive.
     */
    workspaceId?: string | null;
    /**
     * unknown
     *
     * Redacted provider AgentSpec stored with this agent. Auth material is never returned.
     */
    agent?: unknown;
    createdAt: string;
    updatedAt: string;
};

/**
 * a Universally Unique Identifier
 */
export type Uuid = string;

/**
 * maxLength(64)
 *
 * a string at most 64 character(s) long
 */
export type Slug = string;

/**
 * The request did not match the expected schema
 */
export type HttpApiDecodeError = {
    issues: Array<Issue>;
    message: string;
    _tag: 'HttpApiDecodeError';
};

/**
 * Represents an error encountered while parsing a value to match the schema
 */
export type Issue = {
    /**
     * The tag identifying the type of parse issue
     */
    _tag: 'Pointer' | 'Unexpected' | 'Missing' | 'Composite' | 'Refinement' | 'Transformation' | 'Type' | 'Forbidden';
    /**
     * The path to the property where the issue occurred
     */
    path: Array<PropertyKey>;
    /**
     * A descriptive message explaining the issue
     */
    message: string;
};

export type PropertyKey = string | number | {
    _tag: 'symbol';
    key: string;
};

export type R2Error = {
    op: string;
    key: string;
    /**
     * unknown
     */
    cause: unknown;
    _tag: 'R2Error';
};

export type CreateAgentBody = {
    /**
     * maxLength(200)
     *
     * a string at most 200 character(s) long
     */
    name: string;
    description?: string;
    metadata?: {
        [key: string]: string;
    };
    agent?: AgentConfig;
    /**
     * Optional URL-friendly identifier. Auto-derived from `name` if omitted (e.g. `IR Author` → `ir-author`).
     */
    slug?: Slug;
    /**
     * Workspace this agent belongs to. Defaults to the caller's personal workspace if omitted.
     */
    workspaceSlug?: string;
};

export type AgentConfig = {
    harness?: AgentHarness;
    model?: string;
    system?: string;
    workspace?: WorkspaceConfig;
    compute?: ComputeConfig;
    mcp?: AgentMcpConfig;
    permissions?: {
        mode: 'auto' | 'callback' | 'client';
        default?: 'allow' | 'deny';
    };
};

export type AgentHarness = 'think' | 'claude-code';

export type WorkspaceConfig = boolean | string | WorkspaceS3;

export type WorkspaceS3 = {
    provider: 's3';
    bucket: string;
    region?: string;
    credentials?: {
        accessKeyId: string;
        secretAccessKey: string;
    };
    endpoint?: string;
    publicBaseUrl?: string;
};

export type ComputeConfig = boolean | string | ComputeTurbobox;

export type ComputeTurbobox = {
    provider: 'turbobox';
    apiKey: string;
    /**
     * Override the turbobox API base. Defaults to https://sandbox.trilok.ai.
     */
    baseUrl?: string;
    /**
     * Container image. Defaults to a turbobox-side default (alpine for smoke tests).
     */
    image?: string;
    /**
     * CPU shares (turbobox convention). Defaults to provider-side default.
     */
    cpu?: number;
    /**
     * Memory in MB. Defaults to provider-side default.
     */
    memory?: number;
};

export type AgentMcpConfig = Array<McpInstallationConfig>;

export type McpInstallationConfig = {
    name: string;
    server: McpServerUrl;
    toolset?: McpToolsetConfig;
    /**
     * unknown
     */
    options?: unknown;
};

export type McpServerUrl = {
    type: 'url';
    url: string;
    authorizationToken?: string;
    headers?: {
        [key: string]: string;
    };
};

export type McpToolsetConfig = {
    defaultConfig?: McpToolConfig;
    configs?: {
        [key: string]: McpToolConfig;
    };
};

export type McpToolConfig = {
    enabled?: boolean;
    deferLoading?: boolean;
};

export type AgentNotFound = {
    id: string;
    _tag: 'AgentNotFound';
};

export type UpdateAgentBody = {
    /**
     * maxLength(200)
     *
     * a string at most 200 character(s) long
     */
    name?: string;
    description?: string;
    metadata?: {
        [key: string]: string;
    };
    agent?: AgentConfigPatch;
    slug?: Slug;
};

export type AgentConfigPatch = {
    harness: AgentHarness;
    model?: string;
    system?: string;
    workspace?: WorkspaceConfig;
    compute?: ComputeConfig;
    mcp?: AgentMcpConfig;
    permissions?: {
        mode: 'auto' | 'callback' | 'client';
        default?: 'allow' | 'deny';
    };
} | {
    harness?: AgentHarness;
    model: string;
    system?: string;
    workspace?: WorkspaceConfig;
    compute?: ComputeConfig;
    mcp?: AgentMcpConfig;
    permissions?: {
        mode: 'auto' | 'callback' | 'client';
        default?: 'allow' | 'deny';
    };
} | {
    harness?: AgentHarness;
    model?: string;
    system: string;
    workspace?: WorkspaceConfig;
    compute?: ComputeConfig;
    mcp?: AgentMcpConfig;
    permissions?: {
        mode: 'auto' | 'callback' | 'client';
        default?: 'allow' | 'deny';
    };
} | {
    harness?: AgentHarness;
    model?: string;
    system?: string;
    workspace: WorkspaceConfig;
    compute?: ComputeConfig;
    mcp?: AgentMcpConfig;
    permissions?: {
        mode: 'auto' | 'callback' | 'client';
        default?: 'allow' | 'deny';
    };
} | {
    harness?: AgentHarness;
    model?: string;
    system?: string;
    workspace?: WorkspaceConfig;
    compute: ComputeConfig;
    mcp?: AgentMcpConfig;
    permissions?: {
        mode: 'auto' | 'callback' | 'client';
        default?: 'allow' | 'deny';
    };
} | {
    harness?: AgentHarness;
    model?: string;
    system?: string;
    workspace?: WorkspaceConfig;
    compute?: ComputeConfig;
    mcp: AgentMcpConfig;
    permissions?: {
        mode: 'auto' | 'callback' | 'client';
        default?: 'allow' | 'deny';
    };
};

export type Ok = {
    ok: true;
};

export type SkillsList = {
    skills: Array<string>;
};

/**
 * a string matching the pattern ^[a-zA-Z0-9._-]+$
 */
export type SkillName = string;

export type SkillBundle = {
    files: {
        [key: string]: string;
    };
};

export type AgentSessionsList = {
    sessions: Array<AgentSessionRef>;
};

export type AgentSessionRef = {
    sessionId: string;
    createdAt: string;
    /**
     * Human-readable session title. NULL until the auto-titler runs.
     */
    title?: string | null;
    /**
     * Session status — queued, running, done, failed, cancelled.
     */
    status?: string;
};

export type WorkspaceListing = {
    files: Array<WorkspaceFile>;
    cursor?: string;
};

export type WorkspaceFile = {
    path: string;
    size: number;
    uploaded: string;
    contentType?: string;
};

export type McpsList = {
    connected: boolean;
    connections: Array<McpConnection>;
};

export type McpConnection = {
    connectionId: string;
    name: string;
    mcpUrl: string;
    iconUrl?: string | null;
    createdAt: string;
    /**
     * unknown
     */
    status?: unknown;
    /**
     * unknown
     */
    serverInfo?: unknown;
    /**
     * unknown
     */
    metadata?: unknown;
};

export type CreateMcpBody = {
    /**
     * maxLength(200)
     *
     * a string at most 200 character(s) long
     */
    name: string;
    /**
     * minLength(1)
     *
     * a string at least 1 character(s) long
     */
    mcpUrl: string;
};

export type CreateMcpResult = {
    created: boolean;
    connectionId?: string;
    setupUrl?: string;
    error?: string;
};

export type ProvidersList = {
    providers: Array<ProviderManifest>;
};

export type ProviderManifest = {
    id: ProviderId;
    name: string;
    offers: Array<CapabilityOffer>;
    docsUrl: string;
    status: 'ready' | 'partial' | 'planned';
    auth: ProviderAuthSpec;
    requiredOptions: Array<string>;
    models: Array<ProviderModelInfo>;
    events: {
        input: Array<string>;
        output: Array<string>;
        toolLevel: boolean;
        notes?: string;
    };
    features: {
        steering: boolean;
        cancel: boolean;
        webhooks: boolean;
        polling: boolean;
        usage: boolean;
        artifacts: boolean;
    };
};

export type ProviderId = 'flamecast/think' | 'flamecast/acp';

export type CapabilityOffer = {
    type: string;
    projections: Array<'native' | 'tool' | 'mcp' | 'mount' | 'env' | 'proxy' | 'http_bridge' | 'context'>;
    semantics?: {
        [key: string]: unknown;
    };
    authSchemes?: Array<'api_key' | 'bearer' | 'oauth_connection' | 'none'>;
    /**
     * unknown
     */
    optionsSchema?: unknown;
    limits?: {
        [key: string]: unknown;
    };
    fidelity: 'full' | 'partial';
};

export type ProviderAuthSpec = {
    type: 'apiKey' | 'bearer' | 'none';
    envVars: Array<string>;
    description?: string;
};

export type ProviderModelInfo = {
    id: string;
    default?: boolean;
    notes?: string;
};

export type ProviderCompatibilityCheckBody = {
    agent: AgentSpec;
    /**
     * unknown
     */
    input?: unknown;
    callbackUrl?: string;
    callbackEvents?: Array<string>;
    permissions?: {
        mode: 'auto' | 'callback' | 'client';
        default?: 'allow' | 'deny';
    };
    metadata?: {
        [key: string]: string;
    };
};

export type AgentSpec = {
    provider: SessionProviderSpec;
    instructions?: string;
    capabilities?: Array<CapabilitySpec>;
    metadata?: {
        [key: string]: string;
    };
};

export type SessionProviderSpec = {
    id: ProviderId;
    model?: string;
    /**
     * unknown
     */
    auth?: unknown;
    /**
     * unknown
     */
    options?: unknown;
};

export type CapabilitySpec = {
    type: string;
    name?: string;
    provider?: ProviderSpec;
    requirements?: {
        [key: string]: unknown;
    };
    headers?: {
        [key: string]: HeaderValueSpec;
    };
    /**
     * unknown
     */
    options?: unknown;
};

export type ProviderSpec = {
    id: string;
    model?: string;
    /**
     * unknown
     */
    auth?: unknown;
    /**
     * unknown
     */
    options?: unknown;
};

export type HeaderValueSpec = {
    secret: string;
    format: string;
} | {
    secret: string;
} | {
    value: string;
};

export type CapabilityResolutionPlan = {
    bindings: Array<CapabilityBinding>;
    issues: Array<ProviderCompatibilityIssue>;
};

export type CapabilityBinding = {
    capability: string;
    provider: {
        id: string;
        model?: string;
        /**
         * unknown
         */
        options?: unknown;
    };
    projection: 'native' | 'tool' | 'mcp' | 'mount' | 'env' | 'proxy' | 'http_bridge' | 'context';
    /**
     * unknown
     */
    descriptor: unknown;
    transport: {
        handle: string;
    };
    auth?: {
        handle: string;
    };
    fidelity: 'full' | 'partial';
    notes?: Array<string>;
};

export type ProviderCompatibilityIssue = {
    path: string;
    code: string;
    message: string;
};

export type InvalidInput = {
    field: string;
    message: string;
    _tag: 'InvalidInput';
};

export type SessionsList = {
    sessions: Array<SessionListItem>;
    cursor?: string;
};

export type SessionListItem = {
    id: string;
    lastAt: string;
    eventCount: number;
    lastEventAt?: string;
};

export type CreateSessionBody = {
    id?: Uuid;
    agentId: Uuid;
    input: string;
    callbackUrl?: CallbackUrl;
    callbackEvents?: Array<string>;
    permissions?: {
        mode: 'auto' | 'callback' | 'client';
        default?: 'allow' | 'deny';
    };
    metadata?: {
        [key: string]: string;
    };
};

/**
 * HTTP(S) URL that receives session.status_changed POSTs when the session status changes.
 */
export type CallbackUrl = string;

export type SessionState = {
    sessionId: Uuid;
    agent: 'claude-code' | 'think' | 'effectctx' | 'acp' | ProviderId;
    /**
     * Where the agent's session runs. **`cloudflare`** is the default — CF Container + R2-backed `/workspace`, recommended for most use cases. **`sprites`** — per-session Fly Sprite (stateful microVM with auto-idle / auto-wake on HTTP, scale-to-zero, free idle). **`modal`** (COMING SOON, currently rejected with HTTP 400) will mount the cloud-claude R2 bucket into a Modal sandbox via CloudBucketMount. **`firebox`** is EXPERIMENTAL — per-turn firebox microVM with R2 FUSE-mounted at `/workspace`. Sandbox lifetime is independent of file lifetime in all four — files persist (in R2 for cloudflare/modal/firebox, in Sprite ext4 for sprites).
     */
    machine?: 'cloudflare' | 'sprites' | 'modal' | 'firebox';
    workspaceEnabled: boolean;
    status: 'created' | 'running' | 'input_required' | 'done' | 'failed' | 'aborted' | 'idle';
    model?: string;
    lastMessage?: string;
    lastTurnAt?: string;
    turnCount: number;
    /**
     * Running total of billed cost for this session in USD micros (1e-6 USD). SUM over `usage_events` for the session. Grows as turns complete; 0 if nothing has been billed yet.
     */
    costMicros?: number;
    error?: string;
    githubInstallationId?: string;
    agentId?: Uuid;
    /**
     * Stable SHA-256 fingerprint of the redacted inline AgentSpec used to create the session. Present for sessions created with `agentSpec`.
     */
    agentFingerprint?: string;
    links?: SessionLinks;
    provider?: ProviderSessionInfo;
};

export type SessionLinks = {
    ui: string;
    state: string;
    events: string;
    live: string;
    observability: string;
};

export type ProviderSessionInfo = {
    id: ProviderId;
    nativeSessionId: string;
    status?: string;
    nativeStatus?: string;
    links?: {
        console?: string;
        branch?: string;
        pullRequest?: string;
    };
    /**
     * unknown
     */
    usage?: unknown;
};

export type SessionConflict = {
    id: string;
    reason: string;
    _tag: 'SessionConflict';
};

export type TurnFailed = {
    id: string;
    error: string;
    _tag: 'TurnFailed';
};

export type GithubTokenMintFailed = {
    /**
     * unknown
     */
    cause: unknown;
    _tag: 'GithubTokenMintFailed';
};

export type SessionNotFound = {
    id: string;
    _tag: 'SessionNotFound';
};

export type SendMessageBody = {
    /**
     * minLength(1)
     *
     * a string at least 1 character(s) long
     */
    message: string;
    async?: boolean;
    callback_url?: CallbackUrl;
    source?: string;
};

export type TurnInProgress = {
    id: string;
    _tag: 'TurnInProgress';
};

export type WorkspaceUnsupported = {
    id: string;
    reason: string;
    _tag: 'WorkspaceUnsupported';
};

export type SessionUsage = {
    sessionId: Uuid;
    /**
     * Running total of billed cost for this session in USD micros (1e-6 USD). Equals SUM of `turns[].costMicros`.
     */
    costMicros: number;
    turns: Array<SessionUsageTurn>;
};

export type SessionUsageTurn = {
    turnId: string;
    model: string;
    inputTokens: number;
    outputTokens: number;
    costMicros: number;
    createdAt: string;
};

export type EventsResponse = {
    events: Array<EventRow>;
    count: number;
    lastSeq?: number;
};

export type EventRow = {
    session_id?: string;
    seq: number;
    at: string;
    type: string;
    tool_name: string;
    tool_use_id: string;
    is_error: boolean;
    text: string;
    /**
     * unknown
     */
    payload: unknown;
    metadata: {
        [key: string]: string;
    };
};

export type ClickhouseError = {
    query: string;
    /**
     * unknown
     */
    cause: unknown;
    _tag: 'ClickhouseError';
};

export type ObservabilityQueryBody = {
    /**
     * minLength(1)
     *
     * a string at least 1 character(s) long
     */
    sql: string;
    maxRows?: number;
    maxSeconds?: number;
};

export type ObservabilityQueryResponse = {
    data: Array<unknown>;
    rows: number;
    /**
     * unknown
     */
    statistics?: unknown;
    /**
     * unknown
     */
    meta?: unknown;
};

export type RuntimesList = {
    runtimes: Array<RuntimeManifest>;
};

export type RuntimeManifest = {
    id: 'think';
    name: string;
    version?: string;
    /**
     * unknown
     */
    agentConfigSchema: unknown;
    events: {
        toolLevel: boolean;
        usage: boolean;
        cost: boolean;
        notes?: string;
    };
    features: {
        steering: boolean;
        cancel: boolean;
        resume: boolean;
        permissions: boolean;
    };
};

export type RuntimeCheckBody = {
    agent: AgentConfig;
    /**
     * unknown
     */
    input?: unknown;
    permissions?: {
        mode: 'auto' | 'callback' | 'client';
        default?: 'allow' | 'deny';
    };
};

export type RuntimeCheckResult = {
    issues: Array<RuntimeCompatibilityIssue>;
    /**
     * unknown
     */
    launchView?: unknown;
};

export type RuntimeCompatibilityIssue = {
    path: string;
    code: string;
    message: string;
};

export type WorkspacesList = {
    workspaces: Array<WorkspaceMeta>;
};

export type WorkspaceMeta = {
    id: Uuid;
    slug: Slug;
    name: string;
    ownerWorkosUserId: string;
    access: 'private' | 'team';
    createdAt: string;
    updatedAt: string;
};

export type CreateWorkspaceBody = {
    /**
     * maxLength(200)
     *
     * a string at most 200 character(s) long
     */
    name: string;
    slug?: Slug;
    access?: 'private' | 'team';
};

export type WorkspaceConflict = {
    slug: string;
    reason: string;
    _tag: 'WorkspaceConflict';
};

export type WorkspaceNotFound = {
    slug: string;
    _tag: 'WorkspaceNotFound';
};

export type UpdateWorkspaceBody = {
    /**
     * maxLength(200)
     *
     * a string at most 200 character(s) long
     */
    name?: string;
    access?: 'private' | 'team';
};

export type WorkspaceForbidden = {
    slug: string;
    reason: string;
    _tag: 'WorkspaceForbidden';
};

export type ApiKeysList = {
    apiKeys: Array<ApiKeySummary>;
};

export type ApiKeySummary = {
    id: string;
    name: string;
    createdAt: string;
};

export type CreateApiKeyBody = {
    /**
     * maxLength(120)
     *
     * a string at most 120 character(s) long
     */
    name: string;
};

export type CreatedApiKey = {
    id: string;
    name: string;
    createdAt: string;
    value: string;
};

export type AgentsListData = {
    body?: never;
    path?: never;
    query?: {
        workspace?: string;
    };
    url: '/agents';
};

export type AgentsListErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsListError = AgentsListErrors[keyof AgentsListErrors];

export type AgentsListResponses = {
    /**
     * AgentsList
     */
    200: AgentsList;
};

export type AgentsListResponse = AgentsListResponses[keyof AgentsListResponses];

export type AgentsCreateData = {
    body: CreateAgentBody;
    path?: never;
    query?: never;
    url: '/agents';
};

export type AgentsCreateErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsCreateError = AgentsCreateErrors[keyof AgentsCreateErrors];

export type AgentsCreateResponses = {
    /**
     * AgentMeta
     */
    200: AgentMeta;
};

export type AgentsCreateResponse = AgentsCreateResponses[keyof AgentsCreateResponses];

export type AgentsDeleteData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/agents/{id}';
};

export type AgentsDeleteErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsDeleteError = AgentsDeleteErrors[keyof AgentsDeleteErrors];

export type AgentsDeleteResponses = {
    /**
     * Ok
     */
    200: Ok;
};

export type AgentsDeleteResponse = AgentsDeleteResponses[keyof AgentsDeleteResponses];

export type AgentsGetData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/agents/{id}';
};

export type AgentsGetErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsGetError = AgentsGetErrors[keyof AgentsGetErrors];

export type AgentsGetResponses = {
    /**
     * AgentMeta
     */
    200: AgentMeta;
};

export type AgentsGetResponse = AgentsGetResponses[keyof AgentsGetResponses];

export type AgentsUpdateData = {
    body: UpdateAgentBody;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/agents/{id}';
};

export type AgentsUpdateErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsUpdateError = AgentsUpdateErrors[keyof AgentsUpdateErrors];

export type AgentsUpdateResponses = {
    /**
     * AgentMeta
     */
    200: AgentMeta;
};

export type AgentsUpdateResponse = AgentsUpdateResponses[keyof AgentsUpdateResponses];

export type AgentsListSkillsData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/agents/{id}/skills';
};

export type AgentsListSkillsErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsListSkillsError = AgentsListSkillsErrors[keyof AgentsListSkillsErrors];

export type AgentsListSkillsResponses = {
    /**
     * SkillsList
     */
    200: SkillsList;
};

export type AgentsListSkillsResponse = AgentsListSkillsResponses[keyof AgentsListSkillsResponses];

export type AgentsDeleteSkillData = {
    body?: never;
    path: {
        id: Uuid;
        name: SkillName;
    };
    query?: never;
    url: '/agents/{id}/skills/{name}';
};

export type AgentsDeleteSkillErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsDeleteSkillError = AgentsDeleteSkillErrors[keyof AgentsDeleteSkillErrors];

export type AgentsDeleteSkillResponses = {
    /**
     * Ok
     */
    200: Ok;
};

export type AgentsDeleteSkillResponse = AgentsDeleteSkillResponses[keyof AgentsDeleteSkillResponses];

export type AgentsGetSkillData = {
    body?: never;
    path: {
        id: Uuid;
        name: SkillName;
    };
    query?: never;
    url: '/agents/{id}/skills/{name}';
};

export type AgentsGetSkillErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsGetSkillError = AgentsGetSkillErrors[keyof AgentsGetSkillErrors];

export type AgentsGetSkillResponses = {
    /**
     * SkillBundle
     */
    200: SkillBundle;
};

export type AgentsGetSkillResponse = AgentsGetSkillResponses[keyof AgentsGetSkillResponses];

export type AgentsListSessionsData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/agents/{id}/sessions';
};

export type AgentsListSessionsErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsListSessionsError = AgentsListSessionsErrors[keyof AgentsListSessionsErrors];

export type AgentsListSessionsResponses = {
    /**
     * AgentSessionsList
     */
    200: AgentSessionsList;
};

export type AgentsListSessionsResponse = AgentsListSessionsResponses[keyof AgentsListSessionsResponses];

export type AgentsGetMdData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/agents/{id}/agent';
};

export type AgentsGetMdErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsGetMdError = AgentsGetMdErrors[keyof AgentsGetMdErrors];

export type AgentsGetMdResponses = {
    /**
     * a string
     */
    200: string;
};

export type AgentsGetMdResponse = AgentsGetMdResponses[keyof AgentsGetMdResponses];

export type AgentsPutMdData = {
    body: string;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/agents/{id}/agent';
};

export type AgentsPutMdErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsPutMdError = AgentsPutMdErrors[keyof AgentsPutMdErrors];

export type AgentsPutMdResponses = {
    /**
     * Ok
     */
    200: Ok;
};

export type AgentsPutMdResponse = AgentsPutMdResponses[keyof AgentsPutMdResponses];

export type AgentsWorkspaceData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: {
        prefix?: string;
        cursor?: string;
        limit?: string;
        all?: string;
    };
    url: '/agents/{id}/workspace';
};

export type AgentsWorkspaceErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsWorkspaceError = AgentsWorkspaceErrors[keyof AgentsWorkspaceErrors];

export type AgentsWorkspaceResponses = {
    /**
     * WorkspaceListing
     */
    200: WorkspaceListing;
};

export type AgentsWorkspaceResponse = AgentsWorkspaceResponses[keyof AgentsWorkspaceResponses];

export type AgentsListMcpsData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/agents/{id}/mcps';
};

export type AgentsListMcpsErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsListMcpsError = AgentsListMcpsErrors[keyof AgentsListMcpsErrors];

export type AgentsListMcpsResponses = {
    /**
     * McpsList
     */
    200: McpsList;
};

export type AgentsListMcpsResponse = AgentsListMcpsResponses[keyof AgentsListMcpsResponses];

export type AgentsCreateMcpData = {
    body: CreateMcpBody;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/agents/{id}/mcps';
};

export type AgentsCreateMcpErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsCreateMcpError = AgentsCreateMcpErrors[keyof AgentsCreateMcpErrors];

export type AgentsCreateMcpResponses = {
    /**
     * CreateMcpResult
     */
    200: CreateMcpResult;
};

export type AgentsCreateMcpResponse = AgentsCreateMcpResponses[keyof AgentsCreateMcpResponses];

export type AgentsDeleteMcpData = {
    body?: never;
    path: {
        id: Uuid;
        name: SkillName;
    };
    query?: never;
    url: '/agents/{id}/mcps/{name}';
};

export type AgentsDeleteMcpErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type AgentsDeleteMcpError = AgentsDeleteMcpErrors[keyof AgentsDeleteMcpErrors];

export type AgentsDeleteMcpResponses = {
    /**
     * Ok
     */
    200: Ok;
};

export type AgentsDeleteMcpResponse = AgentsDeleteMcpResponses[keyof AgentsDeleteMcpResponses];

export type ProvidersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/providers';
};

export type ProvidersListErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
};

export type ProvidersListError = ProvidersListErrors[keyof ProvidersListErrors];

export type ProvidersListResponses = {
    /**
     * ProvidersList
     */
    200: ProvidersList;
};

export type ProvidersListResponse = ProvidersListResponses[keyof ProvidersListResponses];

export type ProvidersGetFlamecastData = {
    body?: never;
    path: {
        name: 'think' | 'acp';
    };
    query?: never;
    url: '/providers/flamecast/{name}';
};

export type ProvidersGetFlamecastErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
};

export type ProvidersGetFlamecastError = ProvidersGetFlamecastErrors[keyof ProvidersGetFlamecastErrors];

export type ProvidersGetFlamecastResponses = {
    /**
     * ProviderManifest
     */
    200: ProviderManifest;
};

export type ProvidersGetFlamecastResponse = ProvidersGetFlamecastResponses[keyof ProvidersGetFlamecastResponses];

export type ProvidersCheckFlamecastData = {
    body: ProviderCompatibilityCheckBody;
    path: {
        name: 'think' | 'acp';
    };
    query?: never;
    url: '/providers/flamecast/{name}/check';
};

export type ProvidersCheckFlamecastErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError | InvalidInput;
};

export type ProvidersCheckFlamecastError = ProvidersCheckFlamecastErrors[keyof ProvidersCheckFlamecastErrors];

export type ProvidersCheckFlamecastResponses = {
    /**
     * CapabilityResolutionPlan
     */
    200: CapabilityResolutionPlan;
};

export type ProvidersCheckFlamecastResponse = ProvidersCheckFlamecastResponses[keyof ProvidersCheckFlamecastResponses];

export type SessionsListData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: string;
    };
    url: '/sessions';
};

export type SessionsListErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * R2Error
     */
    500: R2Error;
};

export type SessionsListError = SessionsListErrors[keyof SessionsListErrors];

export type SessionsListResponses = {
    /**
     * SessionsList
     */
    200: SessionsList;
};

export type SessionsListResponse = SessionsListResponses[keyof SessionsListResponses];

export type SessionsCreateData = {
    body: CreateSessionBody;
    path?: never;
    query?: never;
    url: '/sessions';
};

export type SessionsCreateErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError | InvalidInput;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * SessionConflict
     */
    409: SessionConflict;
    /**
     * TurnFailed
     */
    500: TurnFailed | R2Error | GithubTokenMintFailed;
};

export type SessionsCreateError = SessionsCreateErrors[keyof SessionsCreateErrors];

export type SessionsCreateResponses = {
    /**
     * SessionState
     */
    200: SessionState;
};

export type SessionsCreateResponse = SessionsCreateResponses[keyof SessionsCreateResponses];

export type SessionsDeleteData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/sessions/{id}';
};

export type SessionsDeleteErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * SessionNotFound
     */
    404: SessionNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type SessionsDeleteError = SessionsDeleteErrors[keyof SessionsDeleteErrors];

export type SessionsDeleteResponses = {
    /**
     * Ok
     */
    200: Ok;
};

export type SessionsDeleteResponse = SessionsDeleteResponses[keyof SessionsDeleteResponses];

export type SessionsGetData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/sessions/{id}';
};

export type SessionsGetErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * SessionNotFound
     */
    404: SessionNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type SessionsGetError = SessionsGetErrors[keyof SessionsGetErrors];

export type SessionsGetResponses = {
    /**
     * SessionState
     */
    200: SessionState;
};

export type SessionsGetResponse = SessionsGetResponses[keyof SessionsGetResponses];

export type SessionsMessageData = {
    body: SendMessageBody;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/sessions/{id}/messages';
};

export type SessionsMessageErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError | InvalidInput;
    /**
     * SessionNotFound
     */
    404: SessionNotFound;
    /**
     * TurnInProgress
     */
    409: TurnInProgress;
    /**
     * TurnFailed
     */
    500: TurnFailed | R2Error;
};

export type SessionsMessageError = SessionsMessageErrors[keyof SessionsMessageErrors];

export type SessionsMessageResponses = {
    /**
     * SessionState
     */
    200: SessionState;
};

export type SessionsMessageResponse = SessionsMessageResponses[keyof SessionsMessageResponses];

export type SessionsAbortData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/sessions/{id}/abort';
};

export type SessionsAbortErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * SessionNotFound
     */
    404: SessionNotFound;
    /**
     * TurnFailed
     */
    500: TurnFailed | R2Error;
};

export type SessionsAbortError = SessionsAbortErrors[keyof SessionsAbortErrors];

export type SessionsAbortResponses = {
    /**
     * Ok
     */
    200: Ok;
};

export type SessionsAbortResponse = SessionsAbortResponses[keyof SessionsAbortResponses];

export type SessionsCancelData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/sessions/{id}/cancel';
};

export type SessionsCancelErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * SessionNotFound
     */
    404: SessionNotFound;
    /**
     * TurnFailed
     */
    500: TurnFailed | R2Error;
};

export type SessionsCancelError = SessionsCancelErrors[keyof SessionsCancelErrors];

export type SessionsCancelResponses = {
    /**
     * Ok
     */
    200: Ok;
};

export type SessionsCancelResponse = SessionsCancelResponses[keyof SessionsCancelResponses];

export type SessionsWorkspaceData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: {
        prefix?: string;
        cursor?: string;
        limit?: string;
        all?: string;
    };
    url: '/sessions/{id}/workspace';
};

export type SessionsWorkspaceErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError | WorkspaceUnsupported;
    /**
     * SessionNotFound
     */
    404: SessionNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type SessionsWorkspaceError = SessionsWorkspaceErrors[keyof SessionsWorkspaceErrors];

export type SessionsWorkspaceResponses = {
    /**
     * WorkspaceListing
     */
    200: WorkspaceListing;
};

export type SessionsWorkspaceResponse = SessionsWorkspaceResponses[keyof SessionsWorkspaceResponses];

export type SessionsUsageData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/sessions/{id}/usage';
};

export type SessionsUsageErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * SessionNotFound
     */
    404: SessionNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type SessionsUsageError = SessionsUsageErrors[keyof SessionsUsageErrors];

export type SessionsUsageResponses = {
    /**
     * SessionUsage
     */
    200: SessionUsage;
};

export type SessionsUsageResponse = SessionsUsageResponses[keyof SessionsUsageResponses];

export type EventsBySessionData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: {
        since?: string;
        limit?: string;
        tail?: string;
    };
    url: '/sessions/{id}/events';
};

export type EventsBySessionErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * SessionNotFound
     */
    404: SessionNotFound;
    /**
     * R2Error
     */
    500: R2Error | ClickhouseError;
};

export type EventsBySessionError = EventsBySessionErrors[keyof EventsBySessionErrors];

export type EventsBySessionResponses = {
    /**
     * EventsResponse
     */
    200: EventsResponse;
};

export type EventsBySessionResponse = EventsBySessionResponses[keyof EventsBySessionResponses];

export type EventsIngestData = {
    /**
     * unknown
     */
    body: unknown;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/sessions/{id}/events';
};

export type EventsIngestErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError | InvalidInput;
    /**
     * SessionNotFound
     */
    404: SessionNotFound;
    /**
     * TurnInProgress
     */
    409: TurnInProgress;
    /**
     * TurnFailed
     */
    500: TurnFailed | R2Error;
};

export type EventsIngestError = EventsIngestErrors[keyof EventsIngestErrors];

export type EventsIngestResponses = {
    /**
     * Ok
     */
    200: Ok;
};

export type EventsIngestResponse = EventsIngestResponses[keyof EventsIngestResponses];

export type EventsCrossData = {
    body?: never;
    path?: never;
    query?: {
        type?: string;
        tool_name?: string;
        session_id?: string;
        since_at?: string;
        limit?: string;
    };
    url: '/events';
};

export type EventsCrossErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * R2Error
     */
    500: R2Error | ClickhouseError;
};

export type EventsCrossError = EventsCrossErrors[keyof EventsCrossErrors];

export type EventsCrossResponses = {
    /**
     * EventsResponse
     */
    200: EventsResponse;
};

export type EventsCrossResponse = EventsCrossResponses[keyof EventsCrossResponses];

export type EventsObservabilityQueryData = {
    body: ObservabilityQueryBody;
    path?: never;
    query?: never;
    url: '/observability/query';
};

export type EventsObservabilityQueryErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * ClickhouseError
     */
    500: ClickhouseError;
};

export type EventsObservabilityQueryError = EventsObservabilityQueryErrors[keyof EventsObservabilityQueryErrors];

export type EventsObservabilityQueryResponses = {
    /**
     * ObservabilityQueryResponse
     */
    200: ObservabilityQueryResponse;
};

export type EventsObservabilityQueryResponse = EventsObservabilityQueryResponses[keyof EventsObservabilityQueryResponses];

export type MetaRuntimesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/runtimes';
};

export type MetaRuntimesErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
};

export type MetaRuntimesError = MetaRuntimesErrors[keyof MetaRuntimesErrors];

export type MetaRuntimesResponses = {
    /**
     * RuntimesList
     */
    200: RuntimesList;
};

export type MetaRuntimesResponse = MetaRuntimesResponses[keyof MetaRuntimesResponses];

export type MetaRuntimeData = {
    body?: never;
    path: {
        id: 'think';
    };
    query?: never;
    url: '/runtimes/{id}';
};

export type MetaRuntimeErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
};

export type MetaRuntimeError = MetaRuntimeErrors[keyof MetaRuntimeErrors];

export type MetaRuntimeResponses = {
    /**
     * RuntimeManifest
     */
    200: RuntimeManifest;
};

export type MetaRuntimeResponse = MetaRuntimeResponses[keyof MetaRuntimeResponses];

export type MetaRuntimeCheckData = {
    body: RuntimeCheckBody;
    path?: never;
    query?: never;
    url: '/runtimes/check';
};

export type MetaRuntimeCheckErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError | InvalidInput;
};

export type MetaRuntimeCheckError = MetaRuntimeCheckErrors[keyof MetaRuntimeCheckErrors];

export type MetaRuntimeCheckResponses = {
    /**
     * RuntimeCheckResult
     */
    200: RuntimeCheckResult;
};

export type MetaRuntimeCheckResponse = MetaRuntimeCheckResponses[keyof MetaRuntimeCheckResponses];

export type MetaSkillMdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/skill.md';
};

export type MetaSkillMdErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
};

export type MetaSkillMdError = MetaSkillMdErrors[keyof MetaSkillMdErrors];

export type MetaSkillMdResponses = {
    /**
     * a string
     */
    200: string;
};

export type MetaSkillMdResponse = MetaSkillMdResponses[keyof MetaSkillMdResponses];

export type MetaContainerHealthData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/sessions/{id}/_debug/container-health';
};

export type MetaContainerHealthErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * R2Error
     */
    500: R2Error;
};

export type MetaContainerHealthError = MetaContainerHealthErrors[keyof MetaContainerHealthErrors];

export type MetaContainerHealthResponses = {
    /**
     * a string
     */
    200: string;
};

export type MetaContainerHealthResponse = MetaContainerHealthResponses[keyof MetaContainerHealthResponses];

export type WorkspacesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workspaces';
};

export type WorkspacesListErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * R2Error
     */
    500: R2Error;
};

export type WorkspacesListError = WorkspacesListErrors[keyof WorkspacesListErrors];

export type WorkspacesListResponses = {
    /**
     * WorkspacesList
     */
    200: WorkspacesList;
};

export type WorkspacesListResponse = WorkspacesListResponses[keyof WorkspacesListResponses];

export type WorkspacesCreateData = {
    body: CreateWorkspaceBody;
    path?: never;
    query?: never;
    url: '/workspaces';
};

export type WorkspacesCreateErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * WorkspaceConflict
     */
    409: WorkspaceConflict;
    /**
     * R2Error
     */
    500: R2Error;
};

export type WorkspacesCreateError = WorkspacesCreateErrors[keyof WorkspacesCreateErrors];

export type WorkspacesCreateResponses = {
    /**
     * WorkspaceMeta
     */
    200: WorkspaceMeta;
};

export type WorkspacesCreateResponse = WorkspacesCreateResponses[keyof WorkspacesCreateResponses];

export type WorkspacesDeleteData = {
    body?: never;
    path: {
        slug: Slug;
    };
    query?: never;
    url: '/workspaces/{slug}';
};

export type WorkspacesDeleteErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * WorkspaceForbidden
     */
    403: WorkspaceForbidden;
    /**
     * WorkspaceNotFound
     */
    404: WorkspaceNotFound;
    /**
     * WorkspaceConflict
     */
    409: WorkspaceConflict;
    /**
     * R2Error
     */
    500: R2Error;
};

export type WorkspacesDeleteError = WorkspacesDeleteErrors[keyof WorkspacesDeleteErrors];

export type WorkspacesDeleteResponses = {
    /**
     * Ok
     */
    200: Ok;
};

export type WorkspacesDeleteResponse = WorkspacesDeleteResponses[keyof WorkspacesDeleteResponses];

export type WorkspacesGetData = {
    body?: never;
    path: {
        slug: Slug;
    };
    query?: never;
    url: '/workspaces/{slug}';
};

export type WorkspacesGetErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * WorkspaceNotFound
     */
    404: WorkspaceNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type WorkspacesGetError = WorkspacesGetErrors[keyof WorkspacesGetErrors];

export type WorkspacesGetResponses = {
    /**
     * WorkspaceMeta
     */
    200: WorkspaceMeta;
};

export type WorkspacesGetResponse = WorkspacesGetResponses[keyof WorkspacesGetResponses];

export type WorkspacesUpdateData = {
    body: UpdateWorkspaceBody;
    path: {
        slug: Slug;
    };
    query?: never;
    url: '/workspaces/{slug}';
};

export type WorkspacesUpdateErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * WorkspaceForbidden
     */
    403: WorkspaceForbidden;
    /**
     * WorkspaceNotFound
     */
    404: WorkspaceNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type WorkspacesUpdateError = WorkspacesUpdateErrors[keyof WorkspacesUpdateErrors];

export type WorkspacesUpdateResponses = {
    /**
     * WorkspaceMeta
     */
    200: WorkspaceMeta;
};

export type WorkspacesUpdateResponse = WorkspacesUpdateResponses[keyof WorkspacesUpdateResponses];

export type ApiKeysListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api-keys';
};

export type ApiKeysListErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * R2Error
     */
    500: R2Error;
};

export type ApiKeysListError = ApiKeysListErrors[keyof ApiKeysListErrors];

export type ApiKeysListResponses = {
    /**
     * ApiKeysList
     */
    200: ApiKeysList;
};

export type ApiKeysListResponse = ApiKeysListResponses[keyof ApiKeysListResponses];

export type ApiKeysCreateData = {
    body: CreateApiKeyBody;
    path?: never;
    query?: never;
    url: '/api-keys';
};

export type ApiKeysCreateErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * R2Error
     */
    500: R2Error;
};

export type ApiKeysCreateError = ApiKeysCreateErrors[keyof ApiKeysCreateErrors];

export type ApiKeysCreateResponses = {
    /**
     * CreatedApiKey
     */
    200: CreatedApiKey;
};

export type ApiKeysCreateResponse = ApiKeysCreateResponses[keyof ApiKeysCreateResponses];

export type ApiKeysDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api-keys/{id}';
};

export type ApiKeysDeleteErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * R2Error
     */
    500: R2Error;
};

export type ApiKeysDeleteError = ApiKeysDeleteErrors[keyof ApiKeysDeleteErrors];

export type ApiKeysDeleteResponses = {
    /**
     * Ok
     */
    200: Ok;
};

export type ApiKeysDeleteResponse = ApiKeysDeleteResponses[keyof ApiKeysDeleteResponses];

export type IntegrationsUninstallData = {
    body?: never;
    path: {
        id: Uuid;
        provider: 'telegram' | 'slack' | 'discord' | 'github' | 'linear' | 'whatsapp' | 'messenger';
    };
    query?: never;
    url: '/agents/{id}/integrations/{provider}';
};

export type IntegrationsUninstallErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type IntegrationsUninstallError = IntegrationsUninstallErrors[keyof IntegrationsUninstallErrors];

export type IntegrationsUninstallResponses = {
    /**
     * unknown
     *
     * Success
     */
    200: unknown;
};

export type IntegrationsStatusData = {
    body?: never;
    path: {
        id: Uuid;
        provider: 'telegram' | 'slack' | 'discord' | 'github' | 'linear' | 'whatsapp' | 'messenger';
    };
    query?: never;
    url: '/agents/{id}/integrations/{provider}';
};

export type IntegrationsStatusErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type IntegrationsStatusError = IntegrationsStatusErrors[keyof IntegrationsStatusErrors];

export type IntegrationsStatusResponses = {
    /**
     * unknown
     *
     * Success
     */
    200: unknown;
};

export type IntegrationsInstallData = {
    /**
     * unknown
     */
    body: unknown;
    path: {
        id: Uuid;
        provider: 'telegram' | 'slack' | 'discord' | 'github' | 'linear' | 'whatsapp' | 'messenger';
    };
    query?: never;
    url: '/agents/{id}/integrations/{provider}';
};

export type IntegrationsInstallErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError | InvalidInput;
    /**
     * AgentNotFound
     */
    404: AgentNotFound;
    /**
     * R2Error
     */
    500: R2Error;
};

export type IntegrationsInstallError = IntegrationsInstallErrors[keyof IntegrationsInstallErrors];

export type IntegrationsInstallResponses = {
    /**
     * unknown
     *
     * Success
     */
    200: unknown;
};

export type IntegrationsWebhookData = {
    /**
     * unknown
     */
    body: unknown;
    path: {
        id: Uuid;
        provider: 'telegram' | 'slack' | 'discord' | 'github' | 'linear' | 'whatsapp' | 'messenger';
    };
    query?: never;
    url: '/agents/{id}/integrations/{provider}/webhook';
};

export type IntegrationsWebhookErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * R2Error
     */
    500: R2Error;
};

export type IntegrationsWebhookError = IntegrationsWebhookErrors[keyof IntegrationsWebhookErrors];

export type IntegrationsWebhookResponses = {
    /**
     * unknown
     *
     * Success
     */
    200: unknown;
};

export type IntegrationsSlackOAuthCallbackData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/agents/{id}/integrations/slack/oauth-callback';
};

export type IntegrationsSlackOAuthCallbackErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * R2Error
     */
    500: R2Error;
};

export type IntegrationsSlackOAuthCallbackError = IntegrationsSlackOAuthCallbackErrors[keyof IntegrationsSlackOAuthCallbackErrors];

export type IntegrationsSlackOAuthCallbackResponses = {
    /**
     * a string
     */
    200: string;
};

export type IntegrationsSlackOAuthCallbackResponse = IntegrationsSlackOAuthCallbackResponses[keyof IntegrationsSlackOAuthCallbackResponses];

export type IntegrationsSlackEventsData = {
    /**
     * unknown
     */
    body: unknown;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/agents/{id}/integrations/slack/events';
};

export type IntegrationsSlackEventsErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * R2Error
     */
    500: R2Error;
};

export type IntegrationsSlackEventsError = IntegrationsSlackEventsErrors[keyof IntegrationsSlackEventsErrors];

export type IntegrationsSlackEventsResponses = {
    /**
     * unknown
     *
     * Success
     */
    200: unknown;
};
